//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LersMobile.Droid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LersMobile.Droid.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить информацию о точке учёта.
        /// </summary>
        public static string IncidentDetailPage_Error_Load_Description {
            get {
                return ResourceManager.GetString("IncidentDetailPage_Error_Load_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки НС.
        /// </summary>
        public static string IncidentDetailPage_Error_Load_Incident {
            get {
                return ResourceManager.GetString("IncidentDetailPage_Error_Load_Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка закрытия НС.
        /// </summary>
        public static string IncidentDetailPage_Errot_Incident_Close {
            get {
                return ResourceManager.GetString("IncidentDetailPage_Errot_Incident_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НС успешно закрыта.
        /// </summary>
        public static string IncidentDetailPage_IncidentCloseSuccessed {
            get {
                return ResourceManager.GetString("IncidentDetailPage_IncidentCloseSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нештатная ситуация.
        /// </summary>
        public static string IncidentDetailPage_Title {
            get {
                return ResourceManager.GetString("IncidentDetailPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начало периода больше чем дата окончания.
        /// </summary>
        public static string IncidentListPage_Error_DateStart_More_Than_DateEnd {
            get {
                return ResourceManager.GetString("IncidentListPage_Error_DateStart_More_Than_DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан пользователь.
        /// </summary>
        public static string LoginPage_Empty_Login {
            get {
                return ResourceManager.GetString("LoginPage_Empty_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан пароль.
        /// </summary>
        public static string LoginPage_Empty_Password {
            get {
                return ResourceManager.GetString("LoginPage_Empty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан сервер ЛЭРС УЧЁТ.
        /// </summary>
        public static string LoginPage_Empty_Server {
            get {
                return ResourceManager.GetString("LoginPage_Empty_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginPage_Enter {
            get {
                return ResourceManager.GetString("LoginPage_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка подключения.
        /// </summary>
        public static string LoginPage_Error_Connect {
            get {
                return ResourceManager.GetString("LoginPage_Error_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка подключения к серверу.
        /// </summary>
        public static string LoginPage_Error_Connect_to_Server {
            get {
                return ResourceManager.GetString("LoginPage_Error_Connect_to_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string LoginPage_Label_Login {
            get {
                return ResourceManager.GetString("LoginPage_Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginPage_Password {
            get {
                return ResourceManager.GetString("LoginPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес сервера ЛЭРС УЧЁТ.
        /// </summary>
        public static string LoginPage_Server {
            get {
                return ResourceManager.GetString("LoginPage_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать SSL.
        /// </summary>
        public static string LoginPage_UseSsl {
            get {
                return ResourceManager.GetString("LoginPage_UseSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из учётной записи.
        /// </summary>
        public static string MainPage_MenuItem_Exit {
            get {
                return ResourceManager.GetString("MainPage_MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нештатные ситуации.
        /// </summary>
        public static string MainPage_MenuItem_IncidentList {
            get {
                return ResourceManager.GetString("MainPage_MenuItem_IncidentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты учёта.
        /// </summary>
        public static string MainPage_MenuItem_NodeList {
            get {
                return ResourceManager.GetString("MainPage_MenuItem_NodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string MainPage_MenuItem_NotificationList {
            get {
                return ResourceManager.GetString("MainPage_MenuItem_NotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системные отчёты.
        /// </summary>
        public static string MainPage_MenuItem_SystemReports {
            get {
                return ResourceManager.GetString("MainPage_MenuItem_SystemReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суточные.
        /// </summary>
        public static string MeasurePointArchivePage_DeviceDataType_Day {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_DeviceDataType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовые.
        /// </summary>
        public static string MeasurePointArchivePage_DeviceDataType_Hour {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_DeviceDataType_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месячные.
        /// </summary>
        public static string MeasurePointArchivePage_DeviceDataType_Month {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_DeviceDataType_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За сутки.
        /// </summary>
        public static string MeasurePointArchivePage_Period_Day {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_Period_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За месяц.
        /// </summary>
        public static string MeasurePointArchivePage_Period_Month {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_Period_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С начала месяца.
        /// </summary>
        public static string MeasurePointArchivePage_Period_MonthBegin {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_Period_MonthBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За 7 дней.
        /// </summary>
        public static string MeasurePointArchivePage_Period_Week {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_Period_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За 2 недели.
        /// </summary>
        public static string MeasurePointArchivePage_Period_WeekTwo {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_Period_WeekTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребление.
        /// </summary>
        public static string MeasurePointArchivePage_SourceType_Consumption {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_SourceType_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интеграторы.
        /// </summary>
        public static string MeasurePointArchivePage_SourceType_Totals {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_SourceType_Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string MeasurePointArchivePage_Title {
            get {
                return ResourceManager.GetString("MeasurePointArchivePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройство.
        /// </summary>
        public static string MeasurePointCommonPage_Device {
            get {
                return ResourceManager.GetString("MeasurePointCommonPage_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоопрос через.
        /// </summary>
        public static string MeasurePointCommonPage_Label_AutoPoll {
            get {
                return ResourceManager.GetString("MeasurePointCommonPage_Label_AutoPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        public static string MeasurePointCommonPage_Title {
            get {
                return ResourceManager.GetString("MeasurePointCommonPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка опроса текущих.
        /// </summary>
        public static string MeasurePointDataPage_Error_Poll_Current {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_Error_Poll_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки данных.
        /// </summary>
        public static string MeasurePointDataPage_ErrorData_Loaded {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_ErrorData_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string MeasurePointDataPage_Loading {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опрос текущих.
        /// </summary>
        public static string MeasurePointDataPage_Poll_Current {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_Poll_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт опрос текущих....
        /// </summary>
        public static string MeasurePointDataPage_Poll_Current_Loading {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_Poll_Current_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опросить текущие.
        /// </summary>
        public static string MeasurePointDataPage_PollCurrent {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_PollCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось завершить опрос за {0} мин..
        /// </summary>
        public static string MeasurePointDataPage_PollCurrent_Timeout_Error {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_PollCurrent_Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string MeasurePointDataPage_Title {
            get {
                return ResourceManager.GetString("MeasurePointDataPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опрос завершён с ошибкой.
        /// </summary>
        public static string MeasurePointPoller_Error_Poll {
            get {
                return ResourceManager.GetString("MeasurePointPoller_Error_Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допуск заканчивается через {0} дн..
        /// </summary>
        public static string MeasurePointView_Admission_Deadline {
            get {
                return ResourceManager.GetString("MeasurePointView_Admission_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допуск просрочен на {0} дн..
        /// </summary>
        public static string MeasurePointView_Admission_Overdue {
            get {
                return ResourceManager.GetString("MeasurePointView_Admission_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критических НС.
        /// </summary>
        public static string MeasurePointView_CriticalIncident_Count {
            get {
                return ResourceManager.GetString("MeasurePointView_CriticalIncident_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные отсутствуют {0} дн..
        /// </summary>
        public static string MeasurePointView_Overdue_Data {
            get {
                return ResourceManager.GetString("MeasurePointView_Overdue_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочено работ: {0}.
        /// </summary>
        public static string MeasurePointView_OverdueJobCount {
            get {
                return ResourceManager.GetString("MeasurePointView_OverdueJobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нештатных ситуаций: {0}.
        /// </summary>
        public static string MeasurePointView_Warning_Incident_Count {
            get {
                return ResourceManager.GetString("MeasurePointView_Warning_Incident_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно подключиться к серверу ЛЭРС УЧЁТ. Отсутствует адрес сервера или токен..
        /// </summary>
        public static string MobileCore_Connect_Failed {
            get {
                return ResourceManager.GetString("MobileCore_Connect_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребитель:.
        /// </summary>
        public static string NodeCommonPropertiesPage_Customer {
            get {
                return ResourceManager.GetString("NodeCommonPropertiesPage_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить свойства объекта.
        /// </summary>
        public static string NodeCommonPropertiesPage_Error_Load_Detail {
            get {
                return ResourceManager.GetString("NodeCommonPropertiesPage_Error_Load_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживающий:.
        /// </summary>
        public static string NodeCommonPropertiesPage_Serviceman {
            get {
                return ResourceManager.GetString("NodeCommonPropertiesPage_Serviceman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние:.
        /// </summary>
        public static string NodeCommonPropertiesPage_State {
            get {
                return ResourceManager.GetString("NodeCommonPropertiesPage_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        public static string NodeCommonPropertiesPage_Title {
            get {
                return ResourceManager.GetString("NodeCommonPropertiesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить список объектов.
        /// </summary>
        public static string NodeListPage_Error_Loaded {
            get {
                return ResourceManager.GetString("NodeListPage_Error_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа объектов.
        /// </summary>
        public static string NodeListPage_NodeGroup {
            get {
                return ResourceManager.GetString("NodeListPage_NodeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по имени или адресу.
        /// </summary>
        public static string NodeListPage_NodeGroup_Search {
            get {
                return ResourceManager.GetString("NodeListPage_NodeGroup_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки учёта.
        /// </summary>
        public static string NodeMeasurePointsPage_Title {
            get {
                return ResourceManager.GetString("NodeMeasurePointsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект учёта.
        /// </summary>
        public static string NodePropertyPage_Title {
            get {
                return ResourceManager.GetString("NodePropertyPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допуск &apos;{0}&apos; заканчивается через {1} дн..
        /// </summary>
        public static string NodeView_Admission_Deadline {
            get {
                return ResourceManager.GetString("NodeView_Admission_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допуск &apos;{0}&apos; просрочен на {1} дн..
        /// </summary>
        public static string NodeView_Admission_Overdue {
            get {
                return ResourceManager.GetString("NodeView_Admission_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критических НС: {0}.
        /// </summary>
        public static string NodeView_CriticalIncident_Count {
            get {
                return ResourceManager.GetString("NodeView_CriticalIncident_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приближается поверка {0} устр..
        /// </summary>
        public static string NodeView_DueEquipmentCalibrationCount {
            get {
                return ResourceManager.GetString("NodeView_DueEquipmentCalibrationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные отсутствуют {0} дн..
        /// </summary>
        public static string NodeView_Overdue_Data {
            get {
                return ResourceManager.GetString("NodeView_Overdue_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочена поверка {0} устр..
        /// </summary>
        public static string NodeView_OverdueEquipmentCalibrationCount {
            get {
                return ResourceManager.GetString("NodeView_OverdueEquipmentCalibrationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочено работ: {0}.
        /// </summary>
        public static string NodeView_OverdueJobCount {
            get {
                return ResourceManager.GetString("NodeView_OverdueJobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть ошибки.
        /// </summary>
        public static string NodeView_Sate_Error {
            get {
                return ResourceManager.GetString("NodeView_Sate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string NodeView_State_None {
            get {
                return ResourceManager.GetString("NodeView_State_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норма.
        /// </summary>
        public static string NodeView_State_Normal {
            get {
                return ResourceManager.GetString("NodeView_State_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть предупреждения.
        /// </summary>
        public static string NodeView_State_Warning {
            get {
                return ResourceManager.GetString("NodeView_State_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нештатных ситуаций: {0}.
        /// </summary>
        public static string NodeView_Warning_Incident_Count {
            get {
                return ResourceManager.GetString("NodeView_Warning_Incident_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить уведомления.
        /// </summary>
        public static string NotificationCenterPage_Error_Loaded_Notifications {
            get {
                return ResourceManager.GetString("NotificationCenterPage_Error_Loaded_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string NotificationInfoPage_Message {
            get {
                return ResourceManager.GetString("NotificationInfoPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип канала связи.
        /// </summary>
        public static string ResourceHelper_Not_Supported_Communication_Link {
            get {
                return ResourceManager.GetString("ResourceHelper_Not_Supported_Communication_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип важности.
        /// </summary>
        public static string ResourceHelper_Not_Supported_Importance {
            get {
                return ResourceManager.GetString("ResourceHelper_Not_Supported_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип важности НС.
        /// </summary>
        public static string ResourceHelper_Not_Supported_Incident_Importance {
            get {
                return ResourceManager.GetString("ResourceHelper_Not_Supported_Incident_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип системы.
        /// </summary>
        public static string ResourceHelper_Not_Supported_SystemType {
            get {
                return ResourceManager.GetString("ResourceHelper_Not_Supported_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акты.
        /// </summary>
        public static string Text_Acts {
            get {
                return ResourceManager.GetString("Text_Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string Text_All {
            get {
                return ResourceManager.GetString("Text_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛЭРС УЧЁТ.
        /// </summary>
        public static string Text_Application {
            get {
                return ResourceManager.GetString("Text_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть нештатную ситуацию?.
        /// </summary>
        public static string Text_Close_Incident_Full_Confirm {
            get {
                return ResourceManager.GetString("Text_Close_Incident_Full_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть НС.
        /// </summary>
        public static string Text_Close_Incident_Short {
            get {
                return ResourceManager.GetString("Text_Close_Incident_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение ....
        /// </summary>
        public static string Text_Connecting {
            get {
                return ResourceManager.GetString("Text_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Text_Date {
            get {
                return ResourceManager.GetString("Text_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполено.
        /// </summary>
        public static string Text_Done {
            get {
                return ResourceManager.GetString("Text_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось определить формат файла.
        /// </summary>
        public static string Text_Error_Could_not_determine_file_format {
            get {
                return ResourceManager.GetString("Text_Error_Could_not_determine_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки.
        /// </summary>
        public static string Text_Error_Load {
            get {
                return ResourceManager.GetString("Text_Error_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV - Файл данных, разделенных запятыми.
        /// </summary>
        public static string Text_FileFormat_Csv {
            get {
                return ResourceManager.GetString("Text_FileFormat_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF - Формат электронных документов.
        /// </summary>
        public static string Text_FileFormat_Pdf {
            get {
                return ResourceManager.GetString("Text_FileFormat_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF - Расширенный текстовый формат.
        /// </summary>
        public static string Text_FileFormat_Rtf {
            get {
                return ResourceManager.GetString("Text_FileFormat_Rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLS - Формат Microsoft Excel 97-2003.
        /// </summary>
        public static string Text_FileFormat_Xls {
            get {
                return ResourceManager.GetString("Text_FileFormat_Xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX - Формат Microsoft Excel.
        /// </summary>
        public static string Text_FileFormat_Xlsx {
            get {
                return ResourceManager.GetString("Text_FileFormat_Xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёт по всем точкам учёта.
        /// </summary>
        public static string Text_Generate_Report_by_All_MeasurePoint {
            get {
                return ResourceManager.GetString("Text_Generate_Report_by_All_MeasurePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёт по объектам.
        /// </summary>
        public static string Text_Generate_Report_by_Nodes {
            get {
                return ResourceManager.GetString("Text_Generate_Report_by_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string Text_No {
            get {
                return ResourceManager.GetString("Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие.
        /// </summary>
        public static string Text_Others {
            get {
                return ResourceManager.GetString("Text_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ведомость параметров.
        /// </summary>
        public static string Text_ParametersSheet {
            get {
                return ResourceManager.GetString("Text_ParametersSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паспорта.
        /// </summary>
        public static string Text_Passports {
            get {
                return ResourceManager.GetString("Text_Passports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёт.
        /// </summary>
        public static string Text_Report {
            get {
                return ResourceManager.GetString("Text_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёт успешно создан.
        /// </summary>
        public static string Text_Report_successfully_created {
            get {
                return ResourceManager.GetString("Text_Report_successfully_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчёты.
        /// </summary>
        public static string Text_Reports {
            get {
                return ResourceManager.GetString("Text_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос выполняется....
        /// </summary>
        public static string Text_Request_is_running {
            get {
                return ResourceManager.GetString("Text_Request_is_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите объекты учёта и нажмите сформировать отчет.
        /// </summary>
        public static string Text_Select_accounting_objects_and_click_generate_report {
            get {
                return ResourceManager.GetString("Text_Select_accounting_objects_and_click_generate_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестное состояние.
        /// </summary>
        public static string Text_State_Not_Supported {
            get {
                return ResourceManager.GetString("Text_State_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробно.
        /// </summary>
        public static string Text_Summary {
            get {
                return ResourceManager.GetString("Text_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        public static string Text_Total {
            get {
                return ResourceManager.GetString("Text_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Text_Yes {
            get {
                return ResourceManager.GetString("Text_Yes", resourceCulture);
            }
        }
    }
}
